INSERT INTO alunos values("","Vicente Soares Neto", "vicente@gmail.com", "92929292");
INSERT INTO alunos values("","Vidal Pereira da Silva Jr.", "vidal@hotmail.com", "3003010");
INSERT INTO alunos VALUES("", "Waldomiro J. S. Leite","valdomiro@yahoo.com.br" , "3323322");
INSERT INTO alunos VALUES("", "Cristina Gobbi", "cristina@hotmail.com", "8584888");
INSERT INTO alunos VALUES("", "Eduardo Cesar Salomão", "eduardo@terra.com.br" ,"22757575");
INSERT INTO alunos VALUES("", "José Luiz Antunes de Almeida", "jose@gmail.com", "76768787");
INSERT INTO alunos VALUES("", "Claudio Delfini", "claudio@globo.com", "848484");
INSERT INTO alunos VALUES("", "Antonio Carlos de Lourenço",  "antonio@yahoo.com.br", "33633644");
INSERT INTO alunos VALUES("", "José Augusto Figueiredo", "joseaugusto@bol.com.br", "85630439");
INSERT INTO alunos VALUES("", "Antonio Cruz", "antoniocruz@hotmail.com", "85344442");
INSERT INTO alunos VALUES("", "Angelo Eduardo Cesar", "angelo@live.com" , "85894646");
INSERT INTO alunos VALUES("",  "Antonio Seabra", "antonioseabra@icloud.com" ,"8598422");
INSERT INTO alunos VALUES("", "Silvio Lago Pereira",  "silvio@hotmail.com" , "272272");
INSERT INTO alunos VALUES("", "Simonny Ribeiro da Cruz", "simonny@terra.com.br" ,"85304398");
INSERT INTO alunos VALUES("", "Marcelo Chaves Ladeira",  "marcelo@hotmail.com" ,"85757504");
INSERT INTO alunos VALUES("", "Rômulo Oliveira Albuquerque", "romulo@gmail.com " ,"288288");
INSERT INTO alunos VALUES("", "Gorki Starlin da Costa Oliveira", "gorki@hotmail.com" ,"85737373");
INSERT INTO alunos VALUES("", "Mário Gomes da Silva", "mario@icloud.com" ,"85272999");
INSERT INTO alunos VALUES("", "Maria da Silva", "maria@gmail.com" ,"852722929");
INSERT INTO alunos VALUES("", "Giuseppe Gozzi", "giuseppe@hotmail.com" ,"8560604");
INSERT INTO alunos VALUES("", "Luiz Fernando Pereira de Mello",  "luiz@gmail.com" ,"84848382");
INSERT INTO alunos VALUES("", "Amilton Costa Oliveira", "amilton@hotmail.com" ,"85274252");
INSERT INTO alunos VALUES("",  "Ferdinando Natale", "ferdinando@gmail.com " ,"85388388");
INSERT INTO alunos VALUES("",  "Nelso Gauze Bonacorso", "nelso@gmail.com"  ,"602323");
INSERT INTO alunos VALUES("", "André Luiz Manzano", "andre@globo.com" ,"2322929");
INSERT INTO alunos VALUES("",  "Américo Damasceno", "americo@hotmail.com" ,"2403535");
INSERT INTO alunos VALUES("", "Fernando Miguel", "fernando@hotmail.com" ,"200200");
INSERT INTO alunos VALUES("", "Moacyr Lima e Silva", "moacyr@gmail.com" ,"2482929");
INSERT INTO alunos VALUES("", "William Pereira Alves","william@hotmail.com"  ,"4486464");
INSERT INTO alunos VALUES("", "Fernanda Caetano Gois", "fernanda@hotmail.com"  ,"3447676");
INSERT INTO alunos VALUES("", "Marcelo Chaves Ladeira", "marcelo@gmail.com" ,"3685555");
INSERT INTO alunos VALUES("",  "Pedro Luiz Côrtes", "pedro@hotmail.com" ,"842828");
INSERT INTO alunos VALUES("",  "Astrogildo Danubio","astrogildo@live.com"  ,"8842727");
INSERT INTO alunos VALUES("", "Geraldo Cervelin", "geraldo@yahoo.com.br" ,"2085959");
INSERT INTO alunos VALUES("", "Elisberto Nogueira da Silva", "elisberto@live.com" ,"602222");
INSERT INTO alunos VALUES("", "Carlos Roberto Yamamoto", "carlos@hotmail.com"  ,"2803636");
INSERT INTO alunos VALUES("", "Fausto de Paschoal", "fausto@globo.com" ,"2644343");
INSERT INTO alunos VALUES("", "Marcos Freire Antunes", "marcos@terra.com.br" ,"8532032");
INSERT INTO alunos VALUES("", "Élia Yathie Matsumoto",  "elia@hotmail.com"  ,"85240324");
INSERT INTO alunos VALUES("", "Claudio Venancio", "claudio@live.com" ,"8529595");
INSERT INTO alunos VALUES("", "William Pereira Alves", "william@yahoo.com.br" ,"85846969");
INSERT INTO alunos VALUES("", "Ronaldo Oliveira", "ronaldo@gmail.com" ,"85046565");
INSERT INTO alunos VALUES("", "Bartolomeu Silva", "bartolomeu@uol.com.br" ,"27245454");
INSERT INTO alunos VALUES("", "Tiburcio Aguiar", "tiburcio@uol.com.br", "8530422");
INSERT INTO alunos VALUES("",  "Adriana Vieira", "adriana@terra.com.br" ,"4404444");
INSERT INTO alunos VALUES("", "Edvaldo Barbosa", "edvaldo@yahoo.com.br" ,"3923922");
INSERT INTO alunos VALUES("", "Ernesto Gato",  "ernesto@live.com" ,"456456");
INSERT INTO alunos VALUES("",  "Moacyr Passo Dias Aguiar", "moacyr@gmail.com" ,"85323232");
INSERT INTO alunos VALUES("", "João Mão Grande", "joao@gmail.com" ,"82242929");
INSERT INTO alunos VALUES("", "Sandro Sotille", "sandro@icloud.com" ,"85853777");
INSERT INTO alunos VALUES("", "Nelson Lava Jato", "nelson@uol.com.br"  ,"8543636");
INSERT INTO alunos VALUES("", "Samir Salim Sumiu", "samir@terra.com.br" ,"85288288");
INSERT INTO alunos VALUES("", "Délio Jesus Guerrini", "delio@gmail.com" ,"20829292");
INSERT INTO alunos VALUES("", "Francisco Capuano", "francisco@terra.com.br" ,"8552552");
INSERT INTO alunos VALUES("", "Rômulo Albuquerque", "romulo@live.com" ,"8644443");
INSERT INTO alunos VALUES("", "Eustójo Ribeiro", "eustojo@hotmail.com" ,"9239393");
INSERT INTO alunos VALUES("", "José Enio Filoni", "jose@gmail.com" ,"86852626");
INSERT INTO alunos VALUES("", "Adilson da Silva Lima", "adilson@live.com" ,"3043737");
INSERT INTO alunos VALUES("", "Tati Quebra Barraco", "tati@live.com"  ,"8923976");
INSERT INTO alunos VALUES("", "Pepe Neném dos Santos", "pepe_nenem@live.com" ,"85240888");
INSERT INTO alunos VALUES("", "Anteu Fabiano Gasparini", "anteu@terra.com.br" ,"87224222");
INSERT INTO alunos VALUES("", "Fernanda Caetano", " fernanda@yahoo.com.br" ,"8584343");
INSERT INTO alunos VALUES("", "Alisom Lima", "alisom@live.com" ,"3603695");
INSERT INTO alunos VALUES("", "Maria Izabel", "maria_izabel@gmail.com" ,"2082929");
