INSERT INTO livros VALUES("1", "Pascal Avançado", "Marco Cipelli / Otávio Markus", "232", "29", "Técnicos", "Proramação");
INSERT INTO livros VALUES("2", "3D Studio Max 2.0", "Edvaldo Barbosa G. Filho", "392", "58", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("3", "3D Studio R4 - Descobrindo e Conquistando", "Adriana Vieira e Maurício L. S. Marini", "440", "39", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("4", "A Infraestrutura de Lans", "Anteu Fabiano L Gasparini e Francisco Eugênio Barrella", "224", "29", "Informática", "Redes");
INSERT INTO livros VALUES("5", "A Solução para sua Empresa: Exportação", "Steven Dabbah", "184", "27", "Administração", "Geral");
INSERT INTO livros VALUES("6", "Administração de Materiais e da Produção", "Izildo Antunes e Elisberto Nogueira da Silva", "160", "22", "Administração", "Geral");
INSERT INTO livros VALUES("7", "Algoritmos - Lógica para Desenvolvimento de Programação", "José Augusto N. G. Manzano e Jayr Figueiredo de Oliveira", "304", "39", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("8", "Amplificadores Operacionais", "Antonio Carlos Seabra", "212", "32", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("9", "Análise Combinatória e Probabilidade", "Claudio Delfini e Geraldo José Sant\'Anna", "84", "15", "Técnicos", "Matemática");
INSERT INTO livros VALUES("10", "Análise de Circuitos em Corrente Alternada", "Rômulo Oliveira Albuquerque", "144", "28", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("11", "Análise de Circuitos em Corrente Contínua", "Rômulo Oliveira Albuquerque", "192", "28", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("12", "Análise e Projeto de Fontes Chaveadas", "Luiz Fernando Pereira de Mello", "528", "39", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("13", "Aplicações em Visual Basic 5.0 - Contas a Pagar e a Receber", "Adilson da Silva Lima", "304", "37", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("14", "Aplicações em Visual Basic 5.0 - Controle de Estoque", "Adilson da Silva Lima", "360", "43", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("15", "Aplicações em Visual Basic 5.0 - Gerador de Relatórios", "Adilson da Silva Lima", "264", "35", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("16", "Aplicações Práticas do Microcontrolador 8051", "Vidal Pereira da Silva Jr.", "300", "36", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("17", "Aprenda a Ler a Palma da Mão em um Estalar de Dedos", "Linda Domin", "248", "29", "Diversos", "Diversos");
INSERT INTO livros VALUES("18", "Aprenda Praticando Excel 97", "Gorki Starlin da Costa Oliveira", "274", "25", "Informática, Séries Especiais", "Planilhas, Aprenda Praticando");
INSERT INTO livros VALUES("19", "Aprenda Praticando Internet c/ Netscape Comunicator 4.0", "Gorki Starlin da Costa Oliveira", "256", "10", "Promoção", "4652");
INSERT INTO livros VALUES("20", "Aprenda Praticando Internet com Microsoft Explorer 3.0", "Gorki Starlin da Costa Oliveira", "328", "35", "Informática, Séries Especiais", "Internet, Aprenda Praticando");
INSERT INTO livros VALUES("21", "Aprenda Praticando Internet com MS Explorer 4.0", "Gorki Starlin da Costa Oliveira", "240", "31", "Informática, Séries Especiais", "Internet, Aprenda Praticando");
INSERT INTO livros VALUES("22", "Aprenda Praticando Internet com Netscape Navigator 3", "Gorki Starlin da Costa Oliveira", "304", "43", "Informática, Séries Especiais", "Internet, Aprenda Praticando");
INSERT INTO livros VALUES("23", "Aprenda Praticando Netware 4.11 Intranets e Gerenciamento Avançado", "Gorki Starlin da Costa Oliveira", "200", "28", "Informática, Séries Especiais", "Redes, Aprenda Praticando");
INSERT INTO livros VALUES("24", "Aprenda Praticando Novell Netware 4.11", "Gorki Starlin da Costa Oliveira e Cleber Ramos", "400", "48", "Informática, Séries Especiais", "Redes, Aprenda Praticando");
INSERT INTO livros VALUES("25", "Aprenda Praticando Windows 95, Word 97, Excel 97 e Internet", "Gorki Starlin da Costa Oliveira", "504", "53", "Informática, Séries Especiais", "Informática Básica e Processamento de Dados, Aprenda Praticando");
INSERT INTO livros VALUES("26", "Aprenda Praticando Word 97", "Gorki Starlin da Costa Oliveira", "240", "25", "Informática, Séries Especiais", "Editores de Texto, Aprenda Praticando");
INSERT INTO livros VALUES("27", "Aprendendo AutoCAD Release 12  - para DOS", "Waldomiro J. S. Leite", "332", "29", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("28", "Aprendendo Intranets e Extranets com Java 1.1", "Américo Damasceno Jr.", "240", "35", "Informática", "Internet");
INSERT INTO livros VALUES("29", "Aprendendo Programação na Internet com Visual Basic 4.0", "Américo Damasceno Jr.", "312", "10", "Promoção", "3656");
INSERT INTO livros VALUES("30", "AutoArchitect - Arquitetura com AutoCAD", "Simonny Ribeiro da Cruz", "304", "45", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("31", "AutoCAD 12 - Estudos Dirigidos para Arquitetura e Engenharia", "Cristina Gobbi", "488", "20", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("32", "AutoCAD 13 for Windows - Guia Prático", "Marcelo Chaves Ladeira e Claudia Campos N. A. de Lima", "504", "57", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("33", "AutoCAD 14 - Guia Prático", "Marcelo Chaves Ladeira e Claudia Campos N. A. de Lima", "368", "55", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("34", "AutoCAD 14 3D - Teoria e Prática", "Edson de Azevedo Lima", "304", "39", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("35", "AutoCAD R14 - Fundamentos", "Élia Yathie Matsumoto", "240", "32", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("36", "AutoLISP - Linguagem de Programação do AutoCAD", "Élia Yathie Matsumoto", "176", "26", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("37", "Automação - Controle Discreto", "Paulo R. da Silveira e Winderson E. Santos", "256", "35", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("38", "Automação Eletropneumática", "Nelso Gauze Bonacorso e Valdir Noll", "160", "23", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("39", "Automação Industrial", "Ferdinando Natale", "388", "48", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("40", "Banco de Dados em Delphi 3", "William Pereira Alves", "448", "64", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("41", "C Auto-Explicativo", "Pedro Luiz Côrtes", "176", "10", "Promoção", "4210");
INSERT INTO livros VALUES("42", "Cadernos de Atividades- Instalações Elétricas Prediais", "Geraldo Cavalin e Severino Cervelin", "208", "29", "Técnicos", "Eletrotécnica");
INSERT INTO livros VALUES("43", "Circuitos Digitais", "Antonio Carlos de Lourenço, Eduardo Cesar A. Cruz, Sabrina Rodero Ferreira e Salomão Choueri Jr.", "344", "42", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("44", "Circuitos em Corrente Alternada", "Rômulo Oliveira Albuquerque", "288", "35", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("45", "Circuitos em Corrente Contínua", "Antonio Carlos de Lourenço, Eduardo Cesar A. Cruz e Salomão Choueri Jr.", "336", "37", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("46", "Circuitos Magnéticos", "Giuseppe G. Massimo Gozzi", "160", "22", "Técnicos", "Eletrotécnica");
INSERT INTO livros VALUES("47", "Circuitos Seqüenciais e Memórias", "Eduardo Cesar A. Cruz e Salomão Choueri Jr.", "116", "16", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("48", "Clipper 5.3 em Rede", "Gorki Starlin da Costa Oliveira", "408", "10", "Promoção", "3865");
INSERT INTO livros VALUES("49", "Comunicação de Dados - Conceitos Fundamentais", "Vicente Soares Neto", "192", "20", "Técnicos", "Telecomunicações");
INSERT INTO livros VALUES("50", "Conhecendo e Trabalhando com o Delphi 4", "Pedro Luiz Côrtes e  Kazuhiro Shiraishi", "392", "49", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("51", "Conhecendo e Trabalhando com o Toolbook II Instructor 6.0", "Pedro Luiz Côrtes e Antônio Luiz F. Filho", "184", "28", "Informática", "Computação Gráfica");
INSERT INTO livros VALUES("52", "Conhecendo e Trabalhando com o Visual Basic 6.0", "Pedro Luiz Côrtes / Roberto Alessandre Scherr", "322", "46", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("53", "Construindo INTRANET com Windows NT 4.0", "Sidney Galeote", "224", "10", "Promoção", "");
INSERT INTO livros VALUES("54", "Construindo INTRANET com Windows NT 4.0", "Galeote", "0", "10", "Promoção", "4571");
INSERT INTO livros VALUES("55", "Contabilidade Geral - Série Contabilidade Descomplicada", "Moacyr de Lima e Silva", "248", "29", "Administração, Séries Especiais", "Contabilidade, Contabilidade Descomplicada");
INSERT INTO livros VALUES("56", "Conversão Eletromecânica de Energia", "Gilio Aluisio Simone - Renato Crivellari Creppe", "344", "44", "Técnicos", "Eletrotécnica");
INSERT INTO livros VALUES("57", "Corel Photo Paint 8 - Guia Prático", "Fernanda Caetano de Gois", "288", "38", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("58", "CorelDRAW 6.0 - Descobrindo e Conquistando", "William Pereira Alves", "850", "10", "Promoção", "346X");
INSERT INTO livros VALUES("59", "CorelDRAW 6.0 - Guia Prático", "Fernanda Caetano de Gois", "360", "10", "Promoção", "3818");
INSERT INTO livros VALUES("60", "CorelDRAW 7 - Descobrindo e Conquistando", "William Pereira Alves", "584", "59", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("61", "CorelDRAW 7.0 - Guia Prático", "Fernanda Caetano de Gois", "368", "42", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("62", "CorelDRAW 8 - Computação Gráfica e Arte Digital", "Adriana Vieira", "296", "44", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("63", "CorelDRAW 8 - Descobrindo e Conquistando", "William Pereira Alves", "408", "59", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("64", "CorelDRAW 8 - Guia Prático", "Fernanda Caetano de Gois", "344", "45", "Informática", "Desktop e Animação");
INSERT INTO livros VALUES("65", "Criando e Publicando um Site na Internet", "Luciano Murta G. Cardoso e Rogério Soares Ramos", "152", "10", "Promoção", "430X");
INSERT INTO livros VALUES("66", "Curso Prático de Delphi 3", "William Pereira Alves", "216", "29", "Informática, Séries Especiais", "Linguagem de Programação, Curso Prático");
INSERT INTO livros VALUES("67", "Curso Prático de Excel 7.0", "Mário Gomes da Silva", "272", "29", "Informática, Séries Especiais", "Planilhas, Curso Prático");
INSERT INTO livros VALUES("68", "Curso Prático de Excel 97", "Mário Gomes da Silva", "256", "29", "Informática, Séries Especiais", "Planilhas, Curso Prático");
INSERT INTO livros VALUES("69", "Curso Prático de MS Excel 5.0", "Mário Gomes da Silva", "304", "29", "Informática, Séries Especiais", "Planilhas, Curso Prático");
INSERT INTO livros VALUES("71", "Curso Prático de MS Word 6.0", "Mário Gomes da Silva", "272", "29", "Informática, Séries Especiais", "Editores de Texto, Curso Prático");
INSERT INTO livros VALUES("72", "Curso Prático de MS-Access 7.0", "Mário Gomes da Silva", "192", "27", "Informática, Séries Especiais", "Linguagem de Programação, Curso Prático");
INSERT INTO livros VALUES("73", "Curso Prático de MS-Access 97", "Mário Gomes da Silva", "184", "25", "Informática, Séries Especiais", "Linguagem de Programação, Curso Prático");
INSERT INTO livros VALUES("74", "Curso Prático de MS-Word 7", "Mário Gomes da Silva", "272", "29", "Informática, Séries Especiais", "Editores de Texto, Curso Prático");
INSERT INTO livros VALUES("75", "Curso Prático de Visual Basic 5", "José Roberto Varela", "304", "35", "Informática, Séries Especiais", "Linguagem de Programação, Curso Prático");
INSERT INTO livros VALUES("76", "Curso Prático de Windows 3.1", "Mário Gomes da Silva", "208", "26", "Informática, Séries Especiais", "Sistemas Operacionais, Curso Prático");
INSERT INTO livros VALUES("77", "Curso Prático de Windows 95", "Mário Gomes da Silva", "184", "26", "Informática, Séries Especiais", "Sistemas Operacionais, Curso Prático");
INSERT INTO livros VALUES("78", "Curso Prático de Word 97", "Mário Gomes da Silva", "256", "33", "Informática, Séries Especiais", "Editores de Texto, Curso Prático");
INSERT INTO livros VALUES("79", "Custos - Série Contabilidade Descomplicada", "Moacyr de Lima e Silva", "240", "32", "Administração, Séries Especiais", "Contabilidade, Contabilidade Descomplicada");
INSERT INTO livros VALUES("80", "Delphi 3.0 - Programação Visual para Windows", "William Pereira Alves", "456", "52", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("81", "Desenvolvimento de Algoritmos - Uma Nova Abordagem", "Claudio Ferreira Venancio", "152", "21", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("82", "Dispositivos Semicondutores - Tiristores", "José Luiz Antunes de Almeida", "176", "24", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("83", "Dispositivos Semicondutores: Diodos e Transistores", "Angelo Eduardo B. Marques, Antonio Carlos de Lourenço e Eduardo Cesar A. Cruz", "416", "45", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("84", "Elementos de Eletrônica Digital", "Francisco G. Capuano e Ivan Valeije Idoeta", "552", "49", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("85", "Elementos de Máquinas", "Marcos A. C. Freire e Izildo Antunes", "320", "45", "Técnicos", "Mecânica");
INSERT INTO livros VALUES("86", "Elementos de Máquinas", "Sarkis Melconian", "288", "39", "Técnicos", "Mecânica");
INSERT INTO livros VALUES("87", "Eletrônica", "José Eduardo Aiub e Enio Filoni", "216", "29", "Técnicos", "Eletrônica");
INSERT INTO livros VALUES("88", "Eletrotécnica - Aplicação e Instalações Elétricas Industriais", "Délio Pereira Guerrini", "208", "28", "Técnicos", "Eletrotécnica");
INSERT INTO livros VALUES("89", "Encore Básico", "Wilma Tschick e Fausto de Paschoal", "264", "43", "Informática", "Linguagem de Programação");
INSERT INTO livros VALUES("90", "Estatística - Auto-Explicativa", "Nelson Peres da Silva", "184", "26", "Administração", "Estatística");
INSERT INTO livros VALUES("91", "Estruturas de Dados Fundamentais - Conceitos e Aplicações", "Silvio do Lago Pereira", "272", "35", "Informática", "Banco de Dados");
INSERT INTO livros VALUES("92", "Estudo Dirigido de Access 97", "Fernando Bestechi Miguel", "200", "25", "Informática, Séries Especiais", "Linguagem de Programação, Estudo Dirigido");
INSERT INTO livros VALUES("93", "Estudo Dirigido de Algoritmos", "José Augusto N. G. Manzano e Jayr Figueiredo de Oliveira", "240", "32", "Informática, Séries Especiais", "Linguagem de Programação, Estudo Dirigido");
INSERT INTO livros VALUES("94", "Estudo Dirigido de Delphi 3", "José Augusto N. G. Manzano e Sandro Santa V. Mendes", "248", "29", "Informática, Séries Especiais", "Linguagem de Programação, Estudo Dirigido");
INSERT INTO livros VALUES("95", "Estudo Dirigido de Delphi 4", "José Augusto N. G. Manzano e Sandro Santa V. Mendes", "272", "34", "Informática, Séries Especiais", "Linguagem de Programação, Estudo Dirigido");
INSERT INTO livros VALUES("96", "Estudo Dirigido de Estatística Descritiva", "Carlos Takeo Akanime e Roberto Katsuhiro Yamamoto", "280", "36", "Administração, Séries Especiais", "Estatítisca, Estudo Dirigido");
INSERT INTO livros VALUES("97", "Estudo Dirigido de Excel 7.0", "André Luiz N. G. Manzano", "240", "27", "Informática, Séries Especiais", "Planilhas, Estudo Dirigido");
INSERT INTO livros VALUES("98", "Estudo Dirigido de Excel 97", "André Luiz N. G. Manzano", "232", "29", "Informática, Séries Especiais", "Planilhas, Estudo Dirigido");
INSERT INTO livros VALUES("99", "Estudo Dirigido de Informática Básica", "Maria Izabel N. G. Manzano e André Luiz N. G. Manzano", "208", "29", "Informática, Séries Especias", "Informática Básica e Processamento de Dados, Estudo Dirigido");
INSERT INTO livros VALUES("100", "Estudo Dirigido de Internet Explorer 4.0", "João Carlos N. G. Manzano e André Luiz N. G. Manzano", "224", "29", "Informática, Séries Especiais", "Internet, Estudo Dirigido");
INSERT INTO livros VALUES("101", "Estudo Dirigido de Linguagem C", "José Augusto N. G. Manzano", "200", "29", "Informática, Séries Especiais", "Linguagem de Programação, Estudo Dirigido");
